FROM node

WORKDIR /app

# it is optmiized to copy package.json first and then run npm install,
# so that it can cache the npm install step and not run it again if the package.json file has not changed
COPY package.json /app 

RUN npm install

COPY . /app

EXPOSE 80

CMD ["node", "server.js"]